/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'getEvmAddress' : ActorMethod<[], string>,
  'getNewPublicKey' : ActorMethod<[], string>,
  'getPublicKey' : ActorMethod<[], string>,
  'signWithEcdsa' : ActorMethod<[string], string>,
  'signWithEthereum' : ActorMethod<[string], string>,
  'signWithEvmWallet' : ActorMethod<[Uint8Array], string>,
  'verifyWithEcdsa' : ActorMethod<
    [{ 'signature' : string, 'publicKey' : string, 'message' : string }],
    boolean
  >,
  'verifyWithEthereum' : ActorMethod<
    [{ 'signature' : string, 'message' : string, 'ethereumAddress' : string }],
    boolean
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];