/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getEvmAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getNewPublicKey' : IDL.Func([], [IDL.Text], []),
    'getPublicKey' : IDL.Func([], [IDL.Text], ['query']),
    'signWithEcdsa' : IDL.Func([IDL.Text], [IDL.Text], []),
    'signWithEthereum' : IDL.Func([IDL.Text], [IDL.Text], []),
    'signWithEvmWallet' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'verifyWithEcdsa' : IDL.Func(
        [
          IDL.Record({
            'signature' : IDL.Text,
            'publicKey' : IDL.Text,
            'message' : IDL.Text,
          }),
        ],
        [IDL.Bool],
        [],
      ),
    'verifyWithEthereum' : IDL.Func(
        [
          IDL.Record({
            'signature' : IDL.Text,
            'message' : IDL.Text,
            'ethereumAddress' : IDL.Text,
          }),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };