/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface backendInterface {
    createPrivateNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    createSharedNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    deriveKey(): Promise<Uint8Array>;
    deriveKeyWithTransportPublicKey(arg0: Uint8Array): Promise<Uint8Array>;
    derivePrivateKvKey(arg0: string, arg1: bigint): Promise<{
        key_version: bigint;
        input_label: string;
        owner: Principal;
        context_label: string;
        encrypted_key_hex: string;
        public_key_hex: string;
    }>;
    derivePrivateNoteKey(arg0: Principal, arg1: string, arg2: string): Promise<{
        encrypted_key: Uint8Array;
        key_version: bigint;
        input_label: string;
        public_key: Uint8Array;
        owner: Principal;
        context_label: string;
        note_id: string;
    }>;
    deriveSharedNoteKey(arg0: string, arg1: string): Promise<{
        encrypted_key: Uint8Array;
        key_version: bigint;
        input_label: string;
        public_key: Uint8Array;
        owner: Principal;
        context_label: string;
        note_id: string;
    }>;
    describePrivateNote(arg0: Principal, arg1: string): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    describeSharedNote(arg0: string): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    fetchPrivateKv(): Promise<{
        key_version: bigint;
        ciphertext_hex: string;
        owner: Principal;
    }>;
    getPublicKey(): Promise<Uint8Array>;
    grantSharedNoteAccess(arg0: string, arg1: Principal): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    revokeSharedNoteAccess(arg0: string, arg1: Principal): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    rotatePrivateNoteKey(arg0: Principal, arg1: string, arg2: bigint): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    rotateSharedNoteKey(arg0: string, arg1: bigint): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
    storePrivateKv(arg0: Uint8Array, arg1: bigint): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async createPrivateNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.createPrivateNote(arg0, arg1, arg2, arg3, arg4);
        return result;
    }
    async createSharedNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.createSharedNote(arg0, arg1, arg2, arg3, arg4);
        return result;
    }
    async deriveKey(): Promise<Uint8Array> {
        const result = await this.actor.deriveKey();
        return result;
    }
    async deriveKeyWithTransportPublicKey(arg0: Uint8Array): Promise<Uint8Array> {
        const result = await this.actor.deriveKeyWithTransportPublicKey(arg0);
        return result;
    }
    async derivePrivateKvKey(arg0: string, arg1: bigint): Promise<{
        key_version: bigint;
        input_label: string;
        owner: Principal;
        context_label: string;
        encrypted_key_hex: string;
        public_key_hex: string;
    }> {
        const result = await this.actor.derivePrivateKvKey(arg0, arg1);
        return result;
    }
    async derivePrivateNoteKey(arg0: Principal, arg1: string, arg2: string): Promise<{
        encrypted_key: Uint8Array;
        key_version: bigint;
        input_label: string;
        public_key: Uint8Array;
        owner: Principal;
        context_label: string;
        note_id: string;
    }> {
        const result = await this.actor.derivePrivateNoteKey(arg0, arg1, arg2);
        return result;
    }
    async deriveSharedNoteKey(arg0: string, arg1: string): Promise<{
        encrypted_key: Uint8Array;
        key_version: bigint;
        input_label: string;
        public_key: Uint8Array;
        owner: Principal;
        context_label: string;
        note_id: string;
    }> {
        const result = await this.actor.deriveSharedNoteKey(arg0, arg1);
        return result;
    }
    async describePrivateNote(arg0: Principal, arg1: string): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.describePrivateNote(arg0, arg1);
        return result;
    }
    async describeSharedNote(arg0: string): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.describeSharedNote(arg0);
        return result;
    }
    async fetchPrivateKv(): Promise<{
        key_version: bigint;
        ciphertext_hex: string;
        owner: Principal;
    }> {
        const result = await this.actor.fetchPrivateKv();
        return result;
    }
    async getPublicKey(): Promise<Uint8Array> {
        const result = await this.actor.getPublicKey();
        return result;
    }
    async grantSharedNoteAccess(arg0: string, arg1: Principal): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.grantSharedNoteAccess(arg0, arg1);
        return result;
    }
    async revokeSharedNoteAccess(arg0: string, arg1: Principal): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.revokeSharedNoteAccess(arg0, arg1);
        return result;
    }
    async rotatePrivateNoteKey(arg0: Principal, arg1: string, arg2: bigint): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.rotatePrivateNoteKey(arg0, arg1, arg2);
        return result;
    }
    async rotateSharedNoteKey(arg0: string, arg1: bigint): Promise<{
        acl: Array<Principal>;
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.rotateSharedNoteKey(arg0, arg1);
        return result;
    }
    async storePrivateKv(arg0: Uint8Array, arg1: bigint): Promise<{
        key_version: bigint;
        ciphertext_len: bigint;
        owner: Principal;
        nonce_len: bigint;
        note_id: string;
        aad_len: bigint;
    }> {
        const result = await this.actor.storePrivateKv(arg0, arg1);
        return result;
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
