/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface _SERVICE {
  'createPrivateNote' : ActorMethod<
    [string, string, string, string, bigint],
    {
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'createSharedNote' : ActorMethod<
    [string, string, string, string, bigint],
    {
      'acl' : Array<Principal>,
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'deriveKey' : ActorMethod<[], Uint8Array>,
  'deriveKeyWithTransportPublicKey' : ActorMethod<[Uint8Array], Uint8Array>,
  'derivePrivateKvKey' : ActorMethod<
    [string, bigint],
    {
      'key_version' : bigint,
      'input_label' : string,
      'owner' : Principal,
      'context_label' : string,
      'encrypted_key_hex' : string,
      'public_key_hex' : string,
    }
  >,
  'derivePrivateNoteKey' : ActorMethod<
    [Principal, string, string],
    {
      'encrypted_key' : Uint8Array,
      'key_version' : bigint,
      'input_label' : string,
      'public_key' : Uint8Array,
      'owner' : Principal,
      'context_label' : string,
      'note_id' : string,
    }
  >,
  'deriveSharedNoteKey' : ActorMethod<
    [string, string],
    {
      'encrypted_key' : Uint8Array,
      'key_version' : bigint,
      'input_label' : string,
      'public_key' : Uint8Array,
      'owner' : Principal,
      'context_label' : string,
      'note_id' : string,
    }
  >,
  'describePrivateNote' : ActorMethod<
    [Principal, string],
    {
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'describeSharedNote' : ActorMethod<
    [string],
    {
      'acl' : Array<Principal>,
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'fetchPrivateKv' : ActorMethod<
    [],
    { 'key_version' : bigint, 'ciphertext_hex' : string, 'owner' : Principal }
  >,
  'getPublicKey' : ActorMethod<[], Uint8Array>,
  'grantSharedNoteAccess' : ActorMethod<
    [string, Principal],
    {
      'acl' : Array<Principal>,
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'revokeSharedNoteAccess' : ActorMethod<
    [string, Principal],
    {
      'acl' : Array<Principal>,
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'rotatePrivateNoteKey' : ActorMethod<
    [Principal, string, bigint],
    {
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'rotateSharedNoteKey' : ActorMethod<
    [string, bigint],
    {
      'acl' : Array<Principal>,
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
  'storePrivateKv' : ActorMethod<
    [Uint8Array, bigint],
    {
      'key_version' : bigint,
      'ciphertext_len' : bigint,
      'owner' : Principal,
      'nonce_len' : bigint,
      'note_id' : string,
      'aad_len' : bigint,
    }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];