/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'derivePrivateKvEnvelope' : IDL.Func(
        [IDL.Text, IDL.Nat64],
        [
          IDL.Record({
            'key_version' : IDL.Nat,
            'input_label' : IDL.Text,
            'owner' : IDL.Principal,
            'context_label' : IDL.Text,
            'encrypted_key_hex' : IDL.Text,
            'public_key_hex' : IDL.Text,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };