/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'derivePrivateKvKey' : IDL.Func(
        [IDL.Text, IDL.Nat64],
        [
          IDL.Record({
            'key_version' : IDL.Nat,
            'input_label' : IDL.Text,
            'owner' : IDL.Principal,
            'context_label' : IDL.Text,
            'encrypted_key_hex' : IDL.Text,
            'public_key_hex' : IDL.Text,
          }),
        ],
        [],
      ),
    'fetchPrivateKv' : IDL.Func(
        [],
        [
          IDL.Record({
            'key_version' : IDL.Nat,
            'ciphertext_hex' : IDL.Text,
            'owner' : IDL.Principal,
          }),
        ],
        [],
      ),
    'storePrivateKv' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Nat64],
        [
          IDL.Record({
            'key_version' : IDL.Nat,
            'ciphertext_len' : IDL.Nat,
            'owner' : IDL.Principal,
            'nonce_len' : IDL.Nat,
            'note_id' : IDL.Text,
            'aad_len' : IDL.Nat,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };